version: '3.1'

networks:
    mynetwork:
        driver: bridge

services:
    db:
        image: mysql:8.0.31
        container_name: mysql2
        hostname: mysql2
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
            - /mnt/mysql/etc/mysql:/etc/mysql/conf.d
        restart: unless-stopped
        environment:
            #- TZ=America/Sao_Paulo
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: testdb1
            MYSQL_USER: testuser
            MYSQL_PASSWORD: root
        networks:
            - mynetwork
